# Generated by Django 4.2.5 on 2023-10-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0004_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
